name: tnw-web
services:
  node-main:
    container_name: nodetnw
    ports:
      - 127.0.0.1:8080:3000
    environment:
      - clientId=
      - authority=
    restart: always
    image: anhvlttfs/tnw-web:latest
